# pulled from repo
name: "Rubocop"

on: push

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    # If running on a self-hosted runner, check it meets the requirements
    # listed at https://github.com/ruby/setup-ruby#using-self-hosted-runners
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    # This step is not necessary if you add the gem to your Gemfile
    - name: Install Code Scanning integration
      run: cd www/ && bundle add code-scanning-rubocop --version 0.3.0 --skip-install

    - name: Install dependencies
      run: cd www/ && bundle install

    - name: Rubocop run
      run: |
        bash -c "
          cd www/ && bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
          [[ $? -ne 2 ]]
        "

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: www/rubocop.sarif
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: '*'
        # An explicit key for restoring and saving the cache
        key: rubocop
        # The chunk size used to split up large files during upload, in bytes
        upload-chunk-size: 4096000 # optional
