name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v2.3.4
    - uses: rojopolis/spellcheck-github-actions@0.14.0
      name: Spellcheck
      with:
        config_path: spellcheck.yaml
        source_files: docs/_posts/*.md
        task_name: Markdown
